name: Deploy with Docker 🚀

on:
  push:
    branches:
      - main  # Запуск при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Cloning repository
      uses: actions/checkout@v3

    - name: Setting ssh key
      uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Deploy to Server via SSH
      run: |
        ssh -o StrictHostKeyChecking=no root@217.196.99.151 << 'EOF'
          cd site/cutaway

          # Получение последних изменений
          git pull origin main

          # Перезапуск контейнеров
          docker-compose down
          docker-compose build --no-cache
          docker-compose up -d
        EOF
