name: Deploy with Docker 🚀

on:
  push:
    branches:
      - main  # Запуск при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Cloning repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker-Image
      uses: docker/build-push-action@v4
      with:
        context: ./cutaway
        push: true
        tags: hheys/cutaway:latest

    - name: Setting ssh key
      uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Deploy to Server via SSH
      run: |
        ssh -o StrictHostKeyChecking=no root@217.196.99.151 << 'EOF'
          docker pull hheys/cutaway:latest
          docker stop app_backend || true
          docker rm app_backend || true
          docker run -d --name cutaway -p 80:3000 hheys/cutaway:latest
        EOF
